name: Deploy Debian packages

on:
  workflow_call:
    inputs:
      release_type:
        description: "The environment to deploy to"
        type: string
        required: true
      tag:
        description: "Release name to deploy"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      release_type:
        description: "The environment to deploy to"
        type: environment
        required: true
      tag:
        description: "Release name to deploy"
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to unstable
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    concurrency: unstable
    steps:
      - uses: robinraju/release-downloader@4bdb8ee081c9ee08a35320794dd461312ac9e4ad
        with:
          repository: "${{ github.action_repository }}"
          tag: "${{ github.event.inputs.tag }}"
          fileName: "target"

      - name: Push packages to repo
        run: |
          sudo apt-get -y install dput-ng python3-paramiko --no-install-recommends
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan nexus.ingo.ch >> ~/.ssh/known_hosts
          echo "${{ secrets.APT_DESKTOP_REPO_UPLOAD }}" > ~/.ssh/id_rsa
          for dist in target/{debian-*,ubuntu-*}/; do
            dput -c resources/dput-jitsi-desktop.cf jitsi-desktop-${{ github.event.inputs.environment }} ${dist}/*.changes
          done;
